### ISSUE TITLE
onDataReceived never called

### ISSUE THREAD

**Issue by psquizzle** [kenjdavidson/react-native-bluetooth-classic#110]
**Mobile Device Environment**
Using Windows, Android device

**Application Environment**
React native 5.01 aplpha

**Describe the bug**
I am attempting to use a bluetooth gamepad with your library. (Mocute 032x). The device connects however new receives any data from the remote. Using Example app as sample project.

**To Reproduce**
Code from Example app

**Expected behavior**
An event coinciding with keypress

**Screenshots**
Console
![console](https://user-images.githubusercontent.com/53052232/117827776-a199ca00-b2b4-11eb-94cb-d118253a45f3.jpg)

initializeRead() {
    this.disconnectSubscription = RNBluetoothClassic.onDeviceDisconnected(() => this.disconnect(true));
    if (this.state.polling) {
      this.readInterval = setInterval(() => this.performRead(), 5000);
    } else {
      this.readSubscription = this.props.device.onDataReceived(data =>{
/// Never called
        this.onReceivedData(data)}
      );
    }
  }

**Comment by psquizzle** [comment]
Thank you for the quick response. I have tried the newline character and many others now. Still unable to determine what the remote is actually sending.

**Comment by kenjdavidson** [comment]
Not much I can do without more info/specs.
Good luck.

**Comment by rzfzr** [comment]
I know this is a bit late, but for future references: one may try something like this: https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en&gl=US

**Comment by kenjdavidson** [comment]
> I know this is a bit late, but for future references: one may try something like this app, to read the raw input: https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en&gl=US

100% I use this app when testing device to device connections so that I'm sure one end of the connection is consistent.  Thanks for the link.
