### ISSUE TITLE
Problem API isConnected()

### ISSUE THREAD

**Issue by wiseguysby** [kenjdavidson/react-native-bluetooth-classic#12]
I've got a problem with api isConnected(), error :
TypeError: _reactNativeBluetoothClassic.default.isConnected is not a function
TypeError: _reactNativeBluetoothClassic.default.isConnected is not a function

My code 
const connectedDevice = await RNBluetoothClassic.isConnected();
console.log(connectedDevice);

what's solution for this problem?

**Comment by kenjdavidson** [comment]
The function just isn't connected in the javascript file, you can add the following line:

**this.isConnected = nativeModule.isConnected;**

to the following section of ./src/index.js

    this.requestEnable = nativeModule.requestEnable;
    this.isEnabled = nativeModule.isEnabled;
    this.list = nativeModule.list;
    this.connect = nativeModule.connect;
    this.disconnect = nativeModule.disconnect;
    this.writeToDevice = nativeModule.writeToDevice;

I just got my laptop back and will be able to continue testing and merging of the two branches I have on the go to resolve a number of these issues.

**Comment by wiseguysby** [comment]
Ok, thanks for your support
