### ISSUE TITLE
Bluetooth Headphone or headset can't connect 

### ISSUE THREAD

**Issue by SintoAntony** [kenjdavidson/react-native-bluetooth-classic#121]
**Mobile Device Environment**

Provide a list of operating systems on which this issue is relevant.
- Device:  Android

**Application Environment**

Provide information about your development environment:
- React Native version: 0.63.2
- RN Bluetooth Classic version: 1.60.0-rc.16

**Describe the bug**

How can i connect bluetooth audio devices using this library.
I got the device details from fetching `RNBluetoothClassic.getBondedDevices()` method. After that i am checking which device is connected with the `RNBluetoothClassic.isDeviceConnected(address: string)` method got false every time.

And i am connecting to a device with `RNBluetoothClassic.connectToDevice(address: string)` not getting the response.

Is there any option to fix this issue?

**Comment by kenjdavidson** [comment]
If you're looking to use one of the `BluetoothProfile`(s) you cannot.  But you can use one of the most recent forks of this project, where it looks like someone re-designed it specifically for `BluetoothProfile`(s).  So check that out.  This is solely for RFComm connections.
