### ISSUE TITLE
iOS Crash sometimes

### ISSUE THREAD

**Issue by cscovino** [kenjdavidson/react-native-bluetooth-classic#136]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: iPad
- OS: iOS 15

**Application Environment**
Provide information about your development environment:
- React Native version: v0.64.1
- RN Bluetooth Classic version: v1.60.0-rc.16

**Describe the bug**
Sometimes after a while that I have connected the BT device, and I have sent and received data the app crashed. I think it could be a problem with memory because the device is always sending data and I see in logs that is constantly saying `Stream %@ has bytes available`. But this is my simple guess.
The Bluetooth device is a LEGO Spike Prime.

The app crashed with this error and occurs in the `DelimitedStringDeviceConnectionImpl.swift` file line 237
```
AppStoreTools:       13A227
AppVariant:          1:iPad7,11:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                unknown
Parent Process:      launchd [1]
Coalition:           es.robotix.c360 [569]

Date/Time:           2021-10-18 17:19:21.2074 -0300
Launch Time:         2021-10-18 16:12:47.2594 -0300
OS Version:          iPhone OS 15.0.2 (19A404)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00004a63d2d1f290
Exception Codes: 0x0000000000000001, 0x00004a63d2d1f290
VM Region Info: 0x4a63d2d1f290 is not in any region.  Bytes after previous region: 81311562855057  
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)     1000000000-7000000000 [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END
Exception Note:  EXC_CORPSE_NOTIFY
Terminating Process: exc handler [481]
Triggered by Thread:  0

...

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000002802ef2a0   x1: 0x000000018883fd00   x2: 0xfffffffffffffff3   x3: 0x0000000280fe9bb3
    x4: 0xfffffffffffa8e00   x5: 0x0000000000000020   x6: 0x00000002802f6990   x7: 0x0000000000000000
    x8: 0x00004a63d2d1f2a0   x9: 0xfffffffe00000000  x10: 0x0000000000000001  x11: 0x0000000100000028
   x12: 0x0000000000000000  x13: 0x6e22202c22626338  x14: 0x227274705f747865  x15: 0x0d7d7d323135203a
   x16: 0x00000001dc89a820  x17: 0x00000001855c5914  x18: 0x0000000000000000  x19: 0x000000016b526710
   x20: 0x000000016b526710  x21: 0x000000011bd34496  x22: 0x000000011bd34400  x23: 0x00000002802ef2a0
   x24: 0x0000000000000000  x25: 0x0000000104c90000  x26: 0x0000000104c8b000  x27: 0x00000001f11d5000
   x28: 0x00000001f11d5000   fp: 0x000000016b526660   lr: 0x0000000188265834
    sp: 0x000000016b526650   pc: 0x000000018883ef28 cpsr: 0x60000000
   esr: 0x92000004 (Data Abort) byte read Translation fault
```
<img width="797" alt="Screen Shot 2021-10-21 at 19 22 18" src="https://user-images.githubusercontent.com/9748855/138365300-872072b6-4b39-44bd-b137-75db3656e346.png">

**Comment by cscovino** [comment]
A good solution could be to implement the `Max Bytes Per Read` with the number as a config parameter.

**Comment by kenjdavidson** [comment]
https://github.com/kenjdavidson/react-native-bluetooth-classic/blob/3dadaca202909a04fc43f61909ca6f345d824a28/android/src/main/java/kjd/reactnative/bluetooth/conn/DelimitedStringDeviceConnectionImpl.java#L55

It looks like the Android version does the message processing during the same step as adding data to the buffer.  This is a pretty easy fix of copying lines 240-243 into the `while()`.

**Comment by kenjdavidson** [comment]
If you can fork the project and play around with each one of these changes, let me know which is best then submit a PR, that would probably be the easiest way.

Rather than me guessing, having it work on my device (which doesn't stream consistently) and not working for you.
