### ISSUE TITLE
[Question] How to pair, write, read after discovery?

### ISSUE THREAD

**Issue by faker007** [kenjdavidson/react-native-bluetooth-classic#138]
**Mobile Device Environment**
On which device(s) would you like this feature to be implemented.   If Android only, the IOS implementations must be created as well - keep not of this for your pull requests.
- Device: LG-7
- OS: API 29, Android 10

**Describe the solution you'd like**

**TL;DR:** So, I would like to ask you my brothers, how to pair, read, write with HC-06... I need a working code snippet I really ask you guys humble

Hello, My brothers, I'm currently doing a project about connecting Arduino(HC-06) and RN with this library.

At first, I was so happy, because the other libraries(react-native-ble-manager, react-native-ble-plx) doesnt work well with HC-06, because I guess those libraries are not support in serial communication. (I'm not sure)

But, with this libray, I could discovery but I realise that I don't know know to pair, write, and read...

Perhaps, I can use pre-made connector for on and off to the LED... 

However, I need some extra feature about Firebase...

So, I would like to ask you my brothers, how to pair, read, write with HC-06...

Thanks for reading...

**Describe alternatives you've considered**

**Additional context**

**Comment by faker007** [comment]
Thanks for reading... I look though docs but I didn't find all in one

**What I tried** is...
`1. const unpaired = await RNBluetoothClassic.stratDiscovery() // it's okay and I got what I want `
`2. const result = await RNBluetoothClassic.pairDevice(element.address); // from one of the unpair variables`

from 2. -> I couldnt pair even, I tried to `RNBluetoothClassic.pairDevice(...)`

**Comment by faker007** [comment]
From now, I successfully paired HC-06 with my Android phone. by using this function `RNBluetoothcLASSIC.connectToDevice(...)`

So, I have to figure out how to write and read the data...

**Comment by kenjdavidson** [comment]
I would suggest looking at the Bluetooth sample app repository. It's got a fully working example. There are also numerous forks/repos that are using this library you can attempt to follow.

Youd also need to confirm/validate your microcontroller code, which is beyond the scope of this issues list.
