### ISSUE TITLE
RNBluetoothClassicPackage.java:68: error: cannot infer type arguments for HashMap<K,V>         this.mConnectionFactories = new HashMap<>() {{                                                ^   reason: cannot use '<>' with anonymous inner classes   where K,V are type-variables:     K extends Object declared in class HashMap     V extends Object declared in class HashMap

### ISSUE THREAD

**Issue by deepakjsr7979** [kenjdavidson/react-native-bluetooth-classic#153]
RNBluetoothClassicPackage.java:68: error: cannot infer type arguments for HashMap<K,V>
        this.mConnectionFactories = new HashMap<>() {{
                                               ^
  reason: cannot use '<>' with anonymous inner classes
  where K,V are type-variables:
    K extends Object declared in class HashMap
    V extends Object declared in class HashMap

**Comment by kenjdavidson** [comment]
This has been fixed in the latest pull request.
I can't remember whether i've released it.

**Comment by kenjdavidson** [comment]
Kicked off a new release with the last PR.
