### ISSUE TITLE
iOS Bluetooth Classic Connection 

### ISSUE THREAD

**Issue by saikat00** [kenjdavidson/react-native-bluetooth-classic#16]
Hi 
We are struggling to connect our small Bluetooth Assitance with iPhone. We want to establish a connection from iPhone end using MAC ID of UUID or Device Name or UDID anything, and as per the readme file I think this library can resolve our issue 

Please confirm us and it's really helpful if you can guide us with some basic functionality of this library

Thanks

**Comment by kenjdavidson** [comment]
Are you able to connect using the BluetoothClassicExample application provided?  This little app should give you a listing of available devices when you open it up, and allow you to connect and send basic data.   Have you followed the instructions on putting your IOS MFi Protocol strings into the file **~/BluetoothClassicExample.plist**? Without that you'll never be able to connect to the device on IOS.
