### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by faizanbutt** [kenjdavidson/react-native-bluetooth-classic#161]
Hi, I got a project from someone else. It is running fine on Android but giving this error on iOS simulator "react_native_bluetooth_classic/RNBluetoothClassic.swift:60: Fatal error: Unexpectedly found nil while unwrapping an Optional value". The simulator screen blanks out and this is the message on Xcode:
<img width="1440" alt="Screenshot 2022-01-05 at 4 38 37 PM" src="https://user-images.githubusercontent.com/28476857/148211783-b3f9b714-c949-408f-8b5c-d84a102fb2f2.png">

**Comment by kenjdavidson** [comment]
You need to provide the `UISupportedExternalAccessoryProtocols`.  There's a big point about this on the documentation site:

https://kenjdavidson.com/react-native-bluetooth-classic/ios/

I haven't bothered handling this gracefully since if you don't have it, nothing will work.

**Comment by kenjdavidson** [comment]
I'm assuming you sorted this out.

**Comment by faizanbutt** [comment]
Yes. Thank you
