### ISSUE TITLE
Can multiple devices connect to a single accepting device at the same time?

### ISSUE THREAD

**Issue by leecaputoit** [kenjdavidson/react-native-bluetooth-classic#163]
Hi, I have been able to successfully perform read/write between two connected devices, but whenever I tried to connect another device to the accepting device, the connection resolves to success yet `getConnectedDevices` only return one entry.

After looking through past issues, it seems that support for multiple connections was indeed added, but I am not sure how to go about enabling it. Any pointers would be appreciated.

**Comment by leecaputoit** [comment]
@kenjdavidson Thanks for the quick response and the informative comment! I did not realize I had to call `cancelAccept` and then start accepting again for a thir d device to connect, now it works perfectly. :)

**Comment by kenjdavidson** [comment]
Ya. I had planned to allow multiple connections in 9me accept session but never got it done. One at a time for the time being.

It should actually resolve the promise and cancel. Accept after the first one anyhow.
