### ISSUE TITLE
IOS Supported?

### ISSUE THREAD

**Issue by sergeu90** [kenjdavidson/react-native-bluetooth-classic#178]
Hello everyone. Great library. 

On android all work as excepted. 

For Ios do you plan supported?

**Comment by kenjdavidson** [comment]
Ios is supported.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: sergeu90 ***@***.***>
Sent: Monday, March 28, 2022 5:28:16 PM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] IOS Supported? (Issue #178)


Hello everyone. Great library.

On android all work as excepted.

For Ios do you plan supported?
