### ISSUE TITLE
Is it possible to run this alone in Expo Go? And not ejecting?

### ISSUE THREAD

**Issue by domzgarcia** [kenjdavidson/react-native-bluetooth-classic#208]
**Mobile Device Environment**
On which device(s) would you like this feature to be implemented.  
Expo Go

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Inquiry

**Describe alternatives you've considered**
Inquiry

**Additional context**
Inquiry

**Comment by kenjdavidson** [comment]
I believe yes, but you need to use the enterprise version of expo. You'll have to look in the docs and go to the library written specifically for go.  If you don't use enterprise then no, I don't believe it is. 

I didn't write it, I've never used it, but the author is a solid guy.
