### ISSUE TITLE
[Question] is there any additional settings for the Eyoyo device?

### ISSUE THREAD

**Issue by rzfzr** [kenjdavidson/react-native-bluetooth-classic#224]
I just bought the eyoyo bar reader device mentioned in the readme by @kenjdavidson 

Connected it via SPP mode to my android device, [this app](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en&gl=US) reads the information from it fine.

However my app with this module, connects fine, but the onDataReceived listener is never triggered, any pointers?

**Comment by kenjdavidson** [comment]
The default delimiter needs to be changed. Either on the app or the scanner. By default it's \n and the other is \n\r.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Rafael Figueira Goncalves ***@***.***>
Sent: Friday, December 16, 2022 11:57:33 AM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Ken Davidson ***@***.***>; Mention ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] [Question] is there any additional settings for the Eyoyo device? (Issue #224)


I just bought the eyoyo bar reader device mentioned in the readme by @kenjdavidson<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson&data=05%7C01%7C%7C81d707efd6744380ecfc08dadf9763f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638068138550963248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S%2BQVn8QGqi1WzWjGc7YnGuaswB7ieSzFDkBfbFkEkfE%3D&reserved=0>

Connected it via SPP mode to my android device, this app<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dde.kai_morich.serial_bluetooth_terminal%26hl%3Den%26gl%3DUS&data=05%7C01%7C%7C81d707efd6744380ecfc08dadf9763f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638068138550963248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9m66aHR35USxe%2FIVMG2AyDKvW3g9J6LX13rvr10gTyw%3D&reserved=0> reads the information from it fine.

However my app with this module, connects fine, but the onDataReceived listener is never triggered, any pointers?

**Comment by rzfzr** [comment]
Perfect, I tried switched around reading the code at the page 19 of the manual, I think it needed to reconnect.
Thanks
