### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by shoks** [kenjdavidson/react-native-bluetooth-classic#235]
Hello, i developed an app with the plugin it work great on android but no way to make it work on iOS even the function isBluetoothEnabled return false like i don't have access to the material. It does not listen to the bluetooth state either. I am wondering if anyone has already experienced something like that on iOS with this plugin. I also coded a native module same thing it like it doesn't see any bluetooth device.

Thanks for helping

**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: iPhone11 Pro Max
- OS: 16.2

**Application Environment**
Provide information about your development environment:
- React Native version: 0.66.4
- RN Bluetooth Classic version: v1.60.0-rc.24

**Comment by kenjdavidson** [comment]
Have you read the documentation?
Do you understand the implications of the MFi protocols?

The library works perfectly with IOS, it was the primary purpose.

Please look into IOS and MFI and feel free to add a new issue with more specific details if you run into problems.
