### ISSUE TITLE
error with expo when executing.  device.read()

### ISSUE THREAD

**Issue by Franckcracko** [kenjdavidson/react-native-bluetooth-classic#237]
**Application Environment**
Provide information about your development environment:
- React Native version: v0.71.3
- RN Bluetooth Classic version: v1.60.0-rc.25
- Expo: v48.0.4

I am currently working on a project in which I have to pass information from a GPS to a bluetooth module in this case the HC-05 with Arduino, the point here is that at the time of I want to read the information (already connected), with the function of read (), this returns a null to which I do not understand why it although I verify before if the connection is established. Eh searched for days the answer, the project is made with expo and EASbuild.

Just like I also have the plugin to implement the library in expo (with-rn-bluetooth-classic)

Code:

```
  async function readDataFromDevice(device) {
    try {
      const data = await device.read();
  
      console.log(data); //return null
    } catch (error) {
      console.error(error);
    }
  }
  
  async function connectToDevice() {
    try {
      const connectedDevice = await 
      RNBluetoothClassic.connectToDevice("XX:XX:XX:XX:XX:XX"); //example address
      
      await connectedDevice.connect({
        CONNECTOR_TYPE: "rfcomm",
        DELIMITER: "\n",
        DEVICE_CHARSET: "utf-8",
      });
      readDataFromDevice(connectedDevice)
      
    } catch (error) {
      console.error(error);
    }
  }
  connectToDevice();

```
what gives me back:
>null

**Comment by kenjdavidson** [comment]
I don't use expo, so you may be on your own debugging this one.  But I will say that

- If you are getting far enough to connect then you should be ok
- If you're getting a NULL on read, the first thing I would do is make sure you are using the right deliminater

Not deliminating messages correctly is usually the issue with getting null read data.
