### ISSUE TITLE
Mobile got freeze when called the buffer data

### ISSUE THREAD

**Issue by priya0pri** [kenjdavidson/react-native-bluetooth-classic#238]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: [e.g. Android, iPhone6]
- OS: [e.g. API19, Nouget, iOS8.1]

**Application Environment**
Provide information about your development environment:
- React Native version: [e.g. v0.61.0]
- RN Bluetooth Classic version: [e.g. v0.10.3]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kenjdavidson** [comment]
Let's try this again with some actual context?
