### ISSUE TITLE
tws earphone connect to iphone without mfi?

### ISSUE THREAD

**Issue by yuan9778** [kenjdavidson/react-native-bluetooth-classic#242]
It seems for ios platform, the device that wants to connect to iPhone must be mfi certified. However, I read from other places (https://apple.stackexchange.com/questions/393007/who-needs-to-join-the-apple-mfi-program) saying for ble 4.0+ device, mif is not required. Recently I wanted to develop an ios app that can manipulate a tws earphone. Just send some simple message to the earphone. I wonder if there is a react-native module that can achieve this without mfi, so I don't need to set up UISupportedExternalAccessoryProtocols because the earphone is not mfi certified.

**Comment by kenjdavidson** [comment]
BLE is not part of the MFi process, that is correct.  No, this library is specific for MFi, if you want to use BLE you want to use another library.
