### ISSUE TITLE
onDeviceDiscovered Duplicated Devices

### ISSUE THREAD

**Issue by ValentinOsvaldo** [kenjdavidson/react-native-bluetooth-classic#249]
Hello

I have an issue with the ```onDeviceDiscovered``` method, it brings duplicated devices. So, looking at the code and reading, I found an issue where it had already been answered, so I wanted to suggest if the device list could be a set to avoid duplicates. Something like this: 

```java
private Set<NativeDevice> mDiscoveredDevices = new HashSet<>();
```

I hope this can solve the issue in some way without causing any major problems, since Java is not my forte.

**Comment by kenjdavidson** [comment]
The issue with this is that each entry has different strength values, so I left it in there to allow for client apps 5o choose what to do with duplicates, which is how I'd prefer it.  There aren't that many, so it's not like it's a major performance hit, and give the power to the caller. 

It should be easy enough for you to set them based on your own rules in Javascript.
