### ISSUE TITLE
`unpairDevice` produces bonding unavailable exception for Android versions >= 19

### ISSUE THREAD

**Issue by chrisdueck** [kenjdavidson/react-native-bluetooth-classic#254]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: Android
- OS: Version >= 19

**Application Environment**
Provide information about your development environment:
- React Native version: 0.71.7
- RN Bluetooth Classic version: 1.60.0-rc.27

**Describe the bug**
This is sort of a follow up from #252, as the issue hasn't been entirely resolved.

Calling `unpairDevice` still doesn't seem to work, but this time the problem appears to be that the check for the SDK version is the wrong way round.

While `pairDevice` errors if `Build.VERSION.SDK_INT < 19`, `unpairDevice` instead errors if `Build.VERSION.SDK_INT >= 19`.

Pairing:
```java
public void pairDevice(String address, Promise promise) {
    if (!checkBluetoothAdapter()) {
        promise.reject(Exceptions.BLUETOOTH_NOT_ENABLED.name(),
                Exceptions.BLUETOOTH_NOT_ENABLED.message());
    } else if (Build.VERSION.SDK_INT < 19) {
        promise.reject(Exceptions.BONDING_UNAVAILABLE_API.name(),
                Exceptions.BONDING_UNAVAILABLE_API.message());
    } else {
       ...
    }
}
```

Unpairing:
```java
public void unpairDevice(String address, Promise promise) {
    if (!checkBluetoothAdapter()) {
        promise.reject(Exceptions.BLUETOOTH_NOT_ENABLED.name(),
                Exceptions.BLUETOOTH_NOT_ENABLED.message());
    } else if (Build.VERSION.SDK_INT >= 19) {
        promise.reject(Exceptions.BONDING_UNAVAILABLE_API.name(),
                Exceptions.BONDING_UNAVAILABLE_API.message());
    } else {
        ...
    }
}
```

I'll put up another PR for this - I've tested the change and all seems to be working now.

**To Reproduce**
1. Pair with a device using pairDevice.
2. Once paired, attempt to unpair using unpairDevice.
3. Device is not unpaired.

**Expected behavior**
Device is unpaired.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by kenjdavidson** [comment]
Thanks!
