### ISSUE TITLE
Can't build APK.

### ISSUE THREAD

**Issue by JayashreePrabakaran** [kenjdavidson/react-native-bluetooth-classic#257]
I can' able to build the APK on android.

When I am building

AAPT: error: resource android:attr/lStar not found.

 error came like this.

Just referred to this #202 .but can't understand it clearly. error is the same. can someone clarify how to resolve this issue?

Thanks

**Comment by kenjdavidson** [comment]
Are you using the correct Version of the library, which includes the PR provided in that issue?

**Comment by JayashreePrabakaran** [comment]
yes, im correct version - 0.9.2

**Comment by kenjdavidson** [comment]
Isn't the latest version like `0.64.x` or something along those lines?
