### ISSUE TITLE
Method Not Implemented 

### ISSUE THREAD

**Issue by JayashreePrabakaran** [kenjdavidson/react-native-bluetooth-classic#260]
**Mobile Device Environment**
- OS: IOS

**Application Environment**
- React Native version: [0.71.8]
- RN Bluetooth Classic version: [1.60.0-rc.28]

**Describe the bug**
When I try to use startDiscovery, getBondedDevices, getConnectedDevices, etc method, method not implemented error shows.

What I am missing? What I have to do ?

<img width="1440" alt="Screenshot 2023-06-24 at 4 13 21 PM" src="https://github.com/kenjdavidson/react-native-bluetooth-classic/assets/87711454/a431d68a-5a47-44db-8033-67546c4a478a">

**Comment by JayashreePrabakaran** [comment]
<key>UISupportedExternalAccessoryProtocols</key>
	<array>
		<string>com.apple.m1</string>
	</array>

	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Access bluetooth device over serial connection to document connection features</string>
	
	
I've added these in my plist file

**Comment by kenjdavidson** [comment]
I would suggest:
- reading the documentation
- reading about MFi 

those features are not supported on IOS.
that protocol is not a real protocol.

**Comment by JayashreePrabakaran** [comment]
I'm using this to connect with ESP32.

Where can I get the MFI Protocal for that? 
or this is not supported in IOS?

**Comment by kenjdavidson** [comment]
I don't believe the esp32 is supported.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JayashreePrabakaran** [comment]
Is there any alternative to do that or  do you have any idea on how to do that?

**Comment by kenjdavidson** [comment]
It's it's not mfi certified there is no way to do it with Bluetooth classic.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JayashreePrabakaran** [comment]
Hii

1. Even If I have MFI, We can achieve that?
2. I can't connect able to connect to ESP32 with IOS using this bluetooth classic module?
3. Or I can able to connect to ESP32 using any other module?

can you clarify this

**Comment by kenjdavidson** [comment]
1.  If you have the mfi protocol it will work.
2.  Esp32 is not mfi certified so you can't have the protocol. So you cannot use this library.
3. Not that I'm aware of.

I suggest googling around a little.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
