### ISSUE TITLE
accept() has wrong parameter type

### ISSUE THREAD

**Issue by SteNafH** [kenjdavidson/react-native-bluetooth-classic#265]
The BluetoothModule.accept() method has a wrong parameter type. It expects a Map<string, object> but it should be of type StandardOptions.

![image](https://github.com/kenjdavidson/react-native-bluetooth-classic/assets/91056027/aafe78e4-424e-4a2e-a228-6d5d2b50160c)

**Comment by kenjdavidson** [comment]
Does the pr still need accepting and merging? Or is this resolved without.

**Comment by SteNafH** [comment]
Oh yeah, it does need accepting and merging
