### ISSUE TITLE
Can i use this package to connect and read data from Zebra RFD90 Reader

### ISSUE THREAD

**Issue by ijazbacha** [kenjdavidson/react-native-bluetooth-classic#268]
**Mobile Device Environment**
I only implement for Android
- React Native Version [0.71.4]
- Device: [ Android]

**Additional context**
I am already using this package, and it connects to the RFD Device. However, I am unable to retrieve the scanning data or tags.

**Comment by kenjdavidson** [comment]
Quick look at the specifications, it only uses profiles
```
Bluetooth Profiles
Supported
SPP Profile
HID Profile
Apple iAP2/MFi
```

which means no, this library will not be able to read data from it (although you will connect to it, as you're saying you do) but this library does not support profiles, only Serial Socket communication.  Which, I can't tell if this supports, you'll need to re-open with more information (maybe some links).

Zebra usually provides it's own libraries for communication.
