### ISSUE TITLE
NPM Dependencies in BluetoothClassicExample

### ISSUE THREAD

**Issue by kenjdavidson** [kenjdavidson/react-native-bluetooth-classic#3]
Resolve issues with NPM dependencies within BluetooothClassicExample to make development a little easier.  Currently symlinks are not working and metro config is customized - although this works for an internal project, this does not seem to work for external projects.

**Comment by bodtx** [comment]
I think I had the same problem, need to set the dependencie like this:

`"react-native-bluetooth-serial": "^0.9.0",`

otherwise the `Buffer` module was not founded, even with `npm i `and so on

**Comment by kenjdavidson** [comment]
This is going to keep coming back until I actually get the project updated, so I'm going to close it for now.
