### ISSUE TITLE
java.io.IOException: read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by xudo49** [kenjdavidson/react-native-bluetooth-classic#310]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
Android 
- Device: OPPO Find 9 ( android 10) , SUNMI V2s ( android 11)

**Application Environment**
Provide information about your development environment:
- "react-native": "0.73.4",
- "react-native-bluetooth-classic": "^1.73.0-rc.8",

**Describe the bug**

connect SUNMI to OPPO
when I called connectToDevice method,  it throw this error
      java.io.IOException: read failed, socket might closed or timeout, read ret: -1
      
in the same case SUNMI bundle bluetooth printer I try to connect using connectToDevice method [ it worked ] 
      
**To Reproduce**
1. discovery Device 
2. pair between 2 devices
3. try to use connectToDevice method 

<img width="569" alt="image" src="https://github.com/kenjdavidson/react-native-bluetooth-classic/assets/68051037/40b1aa45-a66a-454d-b8f0-61d53bfb7bba">

**Comment by franzbiely** [comment]
I understand that this is closed, I am experiencing the same error when attempting to connect. I'm also using the react-native version same as mentioned above. I thought that was the main reason but since this ticket is closed, does it mean it worked on that version?
