### ISSUE TITLE
ios calls connectToDevice method returns error

### ISSUE THREAD

**Issue by gonganruyi** [kenjdavidson/react-native-bluetooth-classic#322]
Calling the connectToDevice method on ios returns the error Device is not currently bonded/paired. Is there any correction needed?

iOS 14.2 
"react-native-bluetooth-classic": "1.73.0-rc.8",

**Comment by kenjdavidson** [comment]
What is your device?
Is it mfi certified?
Do you have the protocols?
Is it paired in the system?

So many questions.......
