### ISSUE TITLE
getConnectedDevice returns No bluetooth device connected when device is connected.

### ISSUE THREAD

**Issue by thiago-carrilho** [kenjdavidson/react-native-bluetooth-classic#45]
When I connect to a bluetooth device using the connect() method in the app, getConnectedDevice  returns the connected device as expected.
But when I close the app and open it again, with the device still connected, the method returns No bluetooth device connected.

![image](https://user-images.githubusercontent.com/13802443/76785622-8b69aa00-6794-11ea-82e6-fe6f548def48.png)

I'm using Android.

**Comment by kenjdavidson** [comment]
Ya, that's how things work currently.  `Connected` in terms of the library does NOT meant `Connected` in terms of the platform.  `Connected` in the library means there is currently RFCOMM session with open sockets available for communication.  When you close the app, this session is closed and therefore the device is no longer "`connected`" in the eyes of the application.

There is no way to maintain connection across Activity life cycles (that I'm aware of) as the objects required are not Serializable and therefore not Bundleable.

I get around this by:
- Saving the most recently connected (RFCOMM) device
- Upon start up I see if `list().find(device)` exists and automatically re-connect to it.

Remember:

- PAIRED = Android (and to a lesser extend IOS) know about the device.  Devices are available with `list()`
- CONNECTED = Library has an open RFCOMM (socket) with the device.  Device is available with `getConnectedDevice()`
