### ISSUE TITLE
您好，请问您这组件读取数据和写数据示例在哪里？

### ISSUE THREAD

**Issue by 314863336** [kenjdavidson/react-native-bluetooth-classic#53]
已经连接成功，但是不知道怎么发送一个指令和接收指令的响应，可怜巴巴的求助

**Comment by kenjdavidson** [comment]
Hey. There is a project called Bluetooth Classic Example withing this library. You should be able to laod it up on your environment.

It has two options, manual read or read event. Look in the app.js file and you'll see a bunch of comments in the component did load function.

I'll try to grab the code lines when I turn my computer on.

**Comment by kenjdavidson** [comment]
https://github.com/kenjdavidson/react-native-bluetooth-classic/blob/master/BluetoothClassicExample/App.js

**Comment by 314863336** [comment]
Thanks !!!
