### ISSUE TITLE
connect to paired device

### ISSUE THREAD

**Issue by mannat26** [kenjdavidson/react-native-bluetooth-classic#65]
async listAndConnect() {
    try {
      let devices = await RNBluetoothClassic.list();
      console.log(devices, 'list');
      await RNBluetoothClassic.setEncoding(BTCharsets.ASCII);
      let connectedDevice = await RNBluetoothClassic.connect(devices[4].id);
      console.log(connectedDevice, 'check connected device')
    } catch (err) {
      console.log(err, 'errror while getting connected device');
    }
  }

react native version is 0.63.3,

Issue on connect to paired device, here i get the list of paired device, but when i tried to connect with device using device id it throws an error showing Connection unsuccessful.
I am trying to connect  android phone version 10 with smart watch.

**Comment by kenjdavidson** [comment]
Have the trace? Debug details? Or any outgrew information to help reproduce this? You haven't given much yo go on.

Does the example app connect?

**Comment by mannat26** [comment]
Error: Connection unsuccessful
    at RNBluetoothClassic.promiseMethodWrapper [as connect] (NativeModules.js:103)
    at Eanmple.connectToDevice$ (Example.js:299)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:164
    at tryCallOne (core.js:37)
    at core.js:123 "error on connectToDevice"
  
  I am getting this error while connecting to device.
 no example app throws the same above error

**Comment by kenjdavidson** [comment]
Have you attempted to debug the native code (Android)? You're not really providing much to go on.

I'll try to upgrade it to 0.63.3 when I get a chance and see if it works with my devices.

**Comment by mannat26** [comment]
My requirement is to tracing the heartRate and steps count from the fitness band or smart watch. so I am using above code.

**Comment by kenjdavidson** [comment]
That sounds like you should be using a BLE profile?

**Comment by mannat26** [comment]
no device support BLE profile

**Comment by kenjdavidson** [comment]
You're going to need to provide a lot more information then, some do diligence on your part:
- The name of the device
- Documentation on the device bluetooth information
- Your code repository for me to review
- Some more information from you debugging the native code and getting Native exceptions

Pretty much anything else that might help (if you want my help) to try and resolve this.  I don't have a lot of time, and with the information you've given so far, it'll be impossible for me to do anything remotely useful.

**Comment by saba-coding** [comment]
Hi,

Following the thread i am using react-native 0.63.3 running on ios 14.0.1 with react-native-bluetooth-classic 0.10.10

const list = async () => {
    const device = await RNBluetoothClassic.list();
    console.log('App -> device', device); // []
 };

I get back an empty array even though i am paired with a device any suggestions?

**Comment by kenjdavidson** [comment]
Do you have your MFi protocol list configured correctly?  This is the number one reason most people have issues with IOS.

**Comment by saba-coding** [comment]
I added following lines in my info.plist file as explained in documentation
```
<key>UISupportedExternalAccessoryProtocols</key>
<array>
	<string>com.apple.m1</string>
</array>
<key>NSBluetoothAlwaysUsageDescription</key>
<string>We need access to bluetooth in order to pair with device</string>
```

**Comment by kenjdavidson** [comment]
Ya, that's not a **real** protocol string.  That's only an example of how and where to put it in.  I suggest you spend a bit of time going through the MFi documentation.  Unless you're working with a manufacturer/vendor that you've signed an NDA with, you're probably never going to get the MFi protocol for what you're trying to do.  

You can't just use Bluetooth classic on IOS like you can on Android, Apple's implementation of it is (even though I get why they do things their own way) a complete pain in the ass.

**Comment by saba-coding** [comment]
Thanks for your response

**Comment by AzranAzwer** [comment]
Hi @kenjdavidson , How Can I get MFi documentation to refer the protocol ?

**Comment by kenjdavidson** [comment]
You need to get it from the hardware vendor.

**Comment by AzranAzwer** [comment]
Thank you for the info.
