### ISSUE TITLE
getConnectedDevice is not a function

### ISSUE THREAD

**Issue by bodtx** [kenjdavidson/react-native-bluetooth-classic#7]
When I use this:
`let device = await RNBluetoothClassic.getConnectedDevice();`
on android 7.1 it says:

`_reactNativeBluetoothClassic.default.getConnectedDevice is not a function`

whereas I use this, it works:
`await RNBluetoothClassic.disconnect();`

or

`this.connectToDevice(btBadgeurDevice).then(() =>  RNBluetoothClassic.write("XXXX\r\n")).then(() => RNBluetoothClassic.disconnect());`

any idea, did I miss a thing?

**Comment by kenjdavidson** [comment]
Ya, because I'm not actually using that function I completely didn't realize it wasn't connected to the NativeModule.

**Comment by kenjdavidson** [comment]
I just added the mapping from NativeModule to RNBluetoothClassic.
