### ISSUE TITLE
cannot connect to a device with message "Invalid connector type: rfcomm"

### ISSUE THREAD

**Issue by william-schlegel** [kenjdavidson/react-native-bluetooth-classic#73]
I created an app tested on android with react native (0.63) and react-native-bluetooth-classic (1.60.0)

I try to connect to a raspberry. It works fine with the demo application but when I try to do it with my app, I have this message "Invalid connector type: rfcomm"
Here is my code for connection:
```javascript
export async function connectToDevice(device) {
  console.log(`Attempting connection to device ${device.id}`);
  try {
    let connection = await device.isConnected();
    if (!connection) {
      connection = await device.connect();
    }
    return connection;
  } catch (error) {
    console.log(error.message);
    throw new Error(error.message);
  }
}
```
What is wrong?
thank you!

**Comment by kenjdavidson** [comment]
See issue #71 and let me know if it's the same issue/resolution. It should be resolved with **1.60.0-rc.4**. Let me know.

**Comment by william-schlegel** [comment]
yes, that was it! works perfectly with rc4 (I was using rc3)
Thank you so much, you saved my day 😃

**Comment by kenjdavidson** [comment]
Right on.  Shoot me an email with the finished product, love to see how this is getting used.
