### ISSUE TITLE
[Android] No "device" prop in device.onDataReceived event

### ISSUE THREAD

**Issue by philpettican** [kenjdavidson/react-native-bluetooth-classic#93]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: Android

**Application Environment**
Provide information about your development environment:
- React Native version: v0.60.0
- RN Bluetooth Classic version: v1.60.0-rc.12

**Describe the bug**
When device.onDataReceived fires on Android, the listener is passed a <BluetoothDeviceReadEvent> which is supposed to contain the following:

```
device: BluetoothNativeDevice;
eventType: BluetoothEventType;
timestamp: string;
data: string;
```
However, I only see "data" and "timestamp" props. It looks like both Android and iOS do not return the "eventType" but iOS does return "device" in the map function.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the react-native-bluetooth-classic-apps example app
2. Connect to device in the list (e.g. bluetooth barcode scanner)
3. Trigger the device to send a read event
4. You'll notice that the event in onDataReceived only has "data" and "timestamp" props available

**Expected behaviour**
device.onDataReceived event on Android should contain a "device" prop to be consistent with iOS.

**Screenshots**
![onReceivedData](https://user-images.githubusercontent.com/15366459/111459999-59768500-8713-11eb-826a-984d335bd379.png)

**Additional context**

**Comment by kenjdavidson** [comment]
Merged and released.
