### ISSUE TITLE
onReceivedData receving data but cannot read

### ISSUE THREAD

**Issue by mudaligekosala** [kenjdavidson/react-native-bluetooth-classic#96]
**Mobile Device Environment**
Android

**Application Environment**
React Native 0.62

**Describe the bug**
I can  connect to paired device and get data using onReceiveData method. But i cannot read those data as its not formatted.
`{
    "timestamp": "2021-03-31T16:20:10.591Z",
    "data": "\u0002�\u0002\u0000\u0000\u0000\u0000\u0006\tZ\u0000\u0000\u0001\u000e\u0002\u0003\u0000\u0003C\u0005\u0000T5B\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0002< \u0017\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000V\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000.O\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\b�\u0002UU\n",
    "device": {
        "extra": {},
        "address": "CC:78:AB:5C:E8:EE",
        "bonded": true,
        "id": "CC:78:AB:5C:E8:EE",
        "name": "TygMT"
    }
}`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kenjdavidson** [comment]
Need substantially more information if I'm going to have. A chance at helping.

Did you send that data?
How did you encode it?  Or how is it encoded? 
What are you expecting as the result? What does this represent at the source? 
What are your connection options?

**Comment by mudaligekosala** [comment]
@kenjdavidson Thank you for the response. No I am just trying to receive data. Bluetooth device sending ASCII string.i just tried using default connection options.
```
let connection = await BLCFound.isConnected();
          if (!connection) {
            connection = await BLCFound.connect({
              CONNECTOR_TYPE: "rfcomm",
              DELIMITER: "\n",
              DEVICE_CHARSET: Platform.OS === "ios" ? 1536 : "utf-8",
            });
          }
          console.log("connection",connection)
          if(connection){
      
            try {
              let messages = await BLCFound.available();
              console.log("available",messages)
      
             // if (messages.length > 0) {
                //performRead();
      
                this.readSubscription = BLCFound.onDataReceived((data) => {
                  console.log("onReceivedData",data)
                });
      
           //   }
            } catch (error) {
              console.log(" read error",error)
      
              // Handle accordingly
            }
          
          }else{
          }
```

**Comment by kenjdavidson** [comment]
You sort this out? If so I'm glad. Mind posting what the issue was for myself and others in the future?

**Comment by mudaligekosala** [comment]
@kenjdavidson Yes it was my fault because this Bluetooth device offering BLE,BL-C,someWiredName First i was selected "someWiredName" thats why i didn't got the correct formatted data.I worked perfect with "BL-C" connection and default data. I didn't wanted to update UUID because it worked with default one.

**Comment by kenjdavidson** [comment]
Solid. Glad it's working for you. Have a good one!

**Comment by mudaligekosala** [comment]
@kenjdavidson Thank you for implement this library 😇

**Comment by kenjdavidson** [comment]
I just reworked it a little. But thanks. If you release something cool let me know. Always interested in what this helps make.
